name: harounapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  fluttertoast: ^8.0.8
  provider: ^6.0.0
  permission_handler: ^11.3.1
  jwt_decoder: ^2.0.1
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo-haroon-app.png
    - assets/Facebook_Logo.png
    - assets/google.png